name = "mapa"  # Promeni u "mapa" da match-uje project name

compatibility_date = "2025-12-15"
compatibility_flags = ["nodejs_compat"]  # Ostavi, za googleapis

main = "src/index.js"

[site]
bucket = "./public"

kv_namespaces = [
  { binding = "__STATIC_CONTENT", id = "8d71fb266b4e4ff49accde601f8b9a1c" }  # Koristi stari ID ili novi; dodaj preview_id ako ima≈°
]

[vars]
GOOGLE_SPREADSHEET_ID = "1Id1YjekUHdiWRhAakmYjrqqitufsAwBlYNvXsE9VPak"
