name = "mapa"

compatibility_date = "2025-12-15"
compatibility_flags = ["nodejs_compat"]

main = "src/index.js"

[site]
bucket = "./public"

kv_namespaces = [
  { binding = "__STATIC_CONTENT", id = "8d71fb266b4e4ff49accde601f8b9a1c" }
]

[vars]
GOOGLE_SPREADSHEET_ID = "1Id1YjekUHdiWRhAakmYjrqqitufsAwBlYNvXsE9VPak"
